version: "3.3"
services:
  db:
    image: postgres
    container_name: local_pgdb
    restart: always
    ports:
      - "54320:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    volumes:
      - local_pgdata:/var/lib/postgresql/data
  crm-api:
    container_name: crm-api
    build:
      context: ./
      dockerfile: Dockerfile
    image: crm-api:latest
    ports:
      - 8080:8080

volumes:
  local_pgdata:
    driver: local